export const ADD_PRODUCT_BASKET='ADD_PRODUCT_BASKET';
export const GET_NUMBERS_BASKET='GET_NUMBERS_BASKET';
export const INCREASE_QUANTITY='INCREASE_QUANTITY';
export const DECREASE_QUANTITY='DECREASE_QUANTITY';
export const CLOSE_PRODUCT='CLOSE_PRODUCT';

export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_REQUEST='FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_FAILURE='FETCH_PRODUCTS_FAILURE';
export const CLEAR_CART='CLEAR_CART';